CREATE TABLE IF NOT EXISTS
  public.factions (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    description text NOT NULL,
    parent_faction_id int references factions 
  );

ALTER TABLE public.factions OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.factions FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public factions are viewable by everyone." ON public.factions FOR
SELECT
  USING (true);

ALTER TABLE public.factions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.images (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    file_name text NOT NULL,
    artist text NOT NULL,
    title text NOT NULL
  );

ALTER TABLE public.images OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.images FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public images are viewable by everyone." ON public.images FOR
SELECT
  USING (true);

ALTER TABLE public.images ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.faction_images (
    faction_id int references factions NOT NULL,
    image_id int references images NOT NULL,
    primary key (faction_id, image_id)
  );

ALTER TABLE public.faction_images OWNER TO postgres;

CREATE POLICY "Public faction_images are viewable by everyone." ON public.faction_images FOR
SELECT
  USING (true);

ALTER TABLE public.faction_images ENABLE ROW LEVEL SECURITY;


DO $$
    BEGIN
        CREATE TYPE weapon_categories AS ENUM ('Basic', 'Close combat', 'Heavy', 'Pistol', 'Support', 'Wargear');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END
$$;

CREATE TABLE IF NOT EXISTS
  public.weapons (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    category weapon_categories NOT NULL,
    short_range text NOT NULL,
    long_range text NOT NULL,
    short_to_hit text NOT NULL,
    long_to_hit text NOT NULL,
    strength text NOT NULL,
    damage text NOT NULL,
    save_modifier text NOT NULL,
    armour_penetration text NOT NULL
  );

ALTER TABLE public.weapons OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.weapons FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public weapons are viewable by everyone." ON public.weapons FOR
SELECT
  USING (true);

ALTER TABLE public.weapons ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.equipment_weapons (
    weapon_id int references weapons NOT NULL,
    faction_id int references factions NOT NULL,
    points int NOT NULL,
    category text NOT NULL,
    primary key (weapon_id, faction_id)
  );

ALTER TABLE public.equipment_weapons OWNER TO postgres;

CREATE POLICY "Public faction_images are viewable by everyone." ON public.equipment_weapons FOR
SELECT
  USING (true);

ALTER TABLE public.equipment_weapons ENABLE ROW LEVEL SECURITY;