CREATE TABLE IF NOT EXISTS
  public.factions (
    id int8 generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    description text NOT NULL
  );

ALTER TABLE public.factions OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.factions FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public factions are viewable by everyone." ON public.factions FOR
SELECT
  USING (true);

ALTER TABLE public.factions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.images (
    id int8 generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    file_name text NOT NULL,
    artist text NOT NULL,
    title text NOT NULL
  );

ALTER TABLE public.images OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.images FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public images are viewable by everyone." ON public.images FOR
SELECT
  USING (true);

ALTER TABLE public.images ENABLE ROW LEVEL SECURITY;