CREATE TABLE IF NOT EXISTS
  public.factions (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    description text NOT NULL,
    parent_faction_id int references factions,
    slug text NOT NULL unique
  );
  

ALTER TABLE public.factions OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.factions FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public factions are viewable by everyone." ON public.factions FOR
SELECT
  USING (true);

ALTER TABLE public.factions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.army_lists (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    faction_id int references factions NOT NULL,
    name text NOT NULL,
    description text
  );

ALTER TABLE public.army_lists OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.army_lists FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public army_lists are viewable by everyone." ON public.army_lists FOR
SELECT
  USING (true);

ALTER TABLE public.army_lists ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.images (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    file_name text NOT NULL,
    artist text NOT NULL,
    title text NOT NULL
  );

ALTER TABLE public.images OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.images FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public images are viewable by everyone." ON public.images FOR
SELECT
  USING (true);

ALTER TABLE public.images ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.faction_images (
    faction_id int references factions NOT NULL,
    image_id int references images NOT NULL,
    primary key (faction_id, image_id)
  );

ALTER TABLE public.faction_images OWNER TO postgres;

CREATE POLICY "Public faction_images are viewable by everyone." ON public.faction_images FOR
SELECT
  USING (true);

ALTER TABLE public.faction_images ENABLE ROW LEVEL SECURITY;

DO $$
    BEGIN
        CREATE TYPE weapon_categories AS ENUM ('Basic', 'Close combat', 'Heavy', 'Pistol', 'Grenades', 'Support', 'Wargear');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END
$$;

CREATE TABLE IF NOT EXISTS
  public.weapons (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    category weapon_categories NOT NULL
  );

ALTER TABLE public.weapons OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.weapons FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public weapons are viewable by everyone." ON public.weapons FOR
SELECT
  USING (true);

ALTER TABLE public.weapons ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.weapon_profiles (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    weapon_id int references weapons NOT NULL,
    name text,
    short_range text NOT NULL,
    long_range text NOT NULL,
    short_to_hit text NOT NULL,
    long_to_hit text NOT NULL,
    strength text NOT NULL,
    damage text NOT NULL,
    save_modifier text NOT NULL,
    armour_penetration text NOT NULL
  );

ALTER TABLE public.weapon_profiles OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.weapon_profiles FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public weapon_profiles are viewable by everyone." ON public.weapon_profiles FOR
SELECT
  USING (true);

ALTER TABLE public.weapon_profiles ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.wargear_categories (
    id int generated by default as identity primary key,
    army_list_id int references army_lists NOT NULL,
    category text NOT NULL,
    note text
  );

ALTER TABLE public.wargear_categories OWNER TO postgres;

CREATE POLICY "Public wargear_categories are viewable by everyone." ON public.wargear_categories FOR
SELECT
  USING (true);

ALTER TABLE public.wargear_categories ENABLE ROW LEVEL SECURITY;

DO $$
    BEGIN
        CREATE TYPE equipment_categories AS ENUM ('Armour');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END
$$;

CREATE TABLE IF NOT EXISTS
  public.equipment (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    rule text NOT NULL,
    category equipment_categories NOT NULL
  );

ALTER TABLE public.equipment OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.equipment FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public equipment are viewable by everyone." ON public.equipment FOR
SELECT
  USING (true);

ALTER TABLE public.equipment ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.vehicles (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL
  );

ALTER TABLE public.vehicles OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.vehicles FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public vehicles are viewable by everyone." ON public.vehicles FOR
SELECT
  USING (true);

ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.wargear_items (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    equipment_id int references equipment,   
    weapon_id int references weapons,   
    vehicle_id int references vehicles,   
    wargear_category_id int references wargear_categories NOT NULL,
    points int NOT NULL
  );

ALTER TABLE public.wargear_items OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.wargear_items FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public wargear_items are viewable by everyone." ON public.wargear_items FOR
SELECT
  USING (true);

ALTER TABLE public.wargear_items ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS
  public.weapon_special_rules (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    rule text NOT NULL
  );

ALTER TABLE public.weapon_special_rules OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.weapon_special_rules FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public weapon_special_rules are viewable by everyone." ON public.weapon_special_rules FOR
SELECT
  USING (true);

ALTER TABLE public.weapon_special_rules ENABLE ROW LEVEL SECURITY;



CREATE TABLE IF NOT EXISTS
  public.weapon_profiles_special_rules (
    weapon_profile_id int references weapon_profiles NOT NULL,
    special_rule_id int references weapon_special_rules NOT NULL,
    primary key (weapon_profile_id, special_rule_id)
  );

ALTER TABLE public.weapon_profiles_special_rules OWNER TO postgres;

CREATE POLICY "Public weapon_profiles_special_rules are viewable by everyone." ON public.weapon_profiles_special_rules FOR
SELECT
  USING (true);

ALTER TABLE public.weapon_profiles_special_rules ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.rule_categories (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    position int NOT NULL
  );

ALTER TABLE public.rule_categories OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.rule_categories FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public rule_categories are viewable by everyone." ON public.rule_categories FOR
SELECT
  USING (true);

ALTER TABLE public.rule_categories ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.rules (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    rule text NOT NULL,
    category_id int references rule_categories NOT NULL,
    position int NOT NULL
  );

ALTER TABLE public.rules OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.rules FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public rules are viewable by everyone." ON public.rules FOR
SELECT
  USING (true);

ALTER TABLE public.rules ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.rule_category_images (
    rule_category_id int references rule_categories NOT NULL,
    image_id int references images NOT NULL,
    primary key (rule_category_id, image_id)
  );

ALTER TABLE public.rule_category_images OWNER TO postgres;

CREATE POLICY "Public rule_category_images are viewable by everyone." ON public.rule_category_images FOR
SELECT
  USING (true);

ALTER TABLE public.rule_category_images ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.mission_cards (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    description text,
    primary_objective text NOT NULL,
    secondary_objective text,
    special_rules text,
    origin text NOT NULL
  );

ALTER TABLE public.mission_cards OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.mission_cards FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public mission_cards are viewable by everyone." ON public.mission_cards FOR
SELECT
  USING (true);

ALTER TABLE public.mission_cards ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.strategy_cards (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    description text NOT NULL,
    origin text NOT NULL
  );

ALTER TABLE public.strategy_cards OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.strategy_cards FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public strategy_cards are viewable by everyone." ON public.strategy_cards FOR
SELECT
  USING (true);

ALTER TABLE public.strategy_cards ENABLE ROW LEVEL SECURITY;

DO $$
    BEGIN
        CREATE TYPE psychic_power_decks AS ENUM (
            'Librarian',
            'Inquisition',
            'Adeptus',
            'Ork Weirdboyz',
            'Eldar Seers',
            'Squat',
            'Tyranid',
            'Slaanesh',
            'Tzeentch',
            'Nurgle'
        );
    EXCEPTION
        WHEN duplicate_object THEN null;
    END
$$;

CREATE TABLE IF NOT EXISTS
  public.psychic_power_cards (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    description text NOT NULL,
    force text NOT NULL,
    range text NOT NULL,
    deck psychic_power_decks NOT NULL
  );

ALTER TABLE public.psychic_power_cards OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.psychic_power_cards FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public psychic_power_cards are viewable by everyone." ON public.psychic_power_cards FOR
SELECT
  USING (true);

ALTER TABLE public.psychic_power_cards ENABLE ROW LEVEL SECURITY;



CREATE TABLE IF NOT EXISTS
  public.special_warp_cards (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    description text NOT NULL,
  );

ALTER TABLE public.special_warp_cards OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.special_warp_cards FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public special_warp_cards are viewable by everyone." ON public.special_warp_cards FOR
SELECT
  USING (true);

ALTER TABLE public.special_warp_cards ENABLE ROW LEVEL SECURITY;




CREATE TABLE IF NOT EXISTS
  public.characteristic_profiles (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    M int NOT NULL,
    WS int NOT NULL,
    BS int NOT NULL,
    S int NOT NULL,
    T int NOT NULL,
    W int NOT NULL,
    I int NOT NULL,
    A int NOT NULL,
    Ld int NOT NULL
  );

ALTER TABLE public.characteristic_profiles OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.characteristic_profiles FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public characteristic_profiles are viewable by everyone." ON public.characteristic_profiles FOR
SELECT
  USING (true);

ALTER TABLE public.characteristic_profiles ENABLE ROW LEVEL SECURITY;

DO $$
    BEGIN
        CREATE TYPE unit_types AS ENUM ('Character', 'Squad');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END
$$;

CREATE TABLE IF NOT EXISTS
  public.units (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    profile_description text,
    type unit_types NOT NULL,
    unit_category_id int references unit_categories NOT NULL,
    points int NOT NULL
  );

ALTER TABLE public.units OWNER TO postgres;

CREATE
OR REPLACE TRIGGER handle_updated_at BEFORE
UPDATE ON public.units FOR EACH ROW
EXECUTE FUNCTION extensions.moddatetime ('updated_at');

CREATE POLICY "Public units are viewable by everyone." ON public.units FOR
SELECT
  USING (true);

ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.unit_profiles (
    id int generated by default as identity primary key,
    unit_id int references units NOT NULL,
    characteristic_profile_id int references characteristic_profiles NOT NULL,
    name text NOT NULL,
    armour int references armour,
    min int NOT NULL,
    max int NOT NULL
  );

ALTER TABLE public.unit_profiles OWNER TO postgres;

CREATE POLICY "Public unit_profiles are viewable by everyone." ON public.unit_profiles FOR
SELECT
  USING (true);

ALTER TABLE public.unit_profiles ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.unit_profile_weapons (
    unit_profile_id int NOT NULL references unit_profiles NOT NULL,
    weapon_id int references weapons NOT NULL,   
    primary key (unit_profile_id, weapon_id),
  );

ALTER TABLE public.unit_profile_weapons OWNER TO postgres;

CREATE POLICY "Public unit_profile_weapons are viewable by everyone." ON public.unit_profile_weapons FOR
SELECT
  USING (true);

ALTER TABLE public.unit_profile_weapons ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS
  public.unit_profile_wargear (
    unit_profile_id int NOT NULL references unit_profiles NOT NULL,
    wargear_category_id int references wargear_categories NOT NULL,
    profile_description text,
    primary key (unit_profile_id, wargear_category_id),
  );

ALTER TABLE public.unit_profile_wargear OWNER TO postgres;

CREATE POLICY "Public unit_profile_wargear are viewable by everyone." ON public.unit_profile_wargear FOR
SELECT
  USING (true);

ALTER TABLE public.unit_profile_wargear ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS
  public.unit_categories (
    id int generated by default as identity primary key,
    army_list_id int references army_lists NOT NULL,
    category text NOT NULL,
    position int NOT NULL
  );

ALTER TABLE public.unit_categories OWNER TO postgres;

CREATE POLICY "Public unit_categories are viewable by everyone." ON public.unit_categories FOR
SELECT
  USING (true);

ALTER TABLE public.unit_categories ENABLE ROW LEVEL SECURITY;

DO $$
    BEGIN
        CREATE TYPE save_types AS ENUM ('armour save', 'unmodified save', 'armour save modifier');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END
$$;

CREATE TABLE IF NOT EXISTS
  public.armour (
    id int generated by default as identity primary key,
    created_at timestamp with time zone DEFAULT "now" () NOT NULL,
    updated_at timestamp with time zone,
    name text NOT NULL,
    save text NOT NULL,
    save_type save_types NOT NULL,
    description text NOT NULL
  );

ALTER TABLE public.armour OWNER TO postgres;

CREATE POLICY "Public armour are viewable by everyone." ON public.armour FOR
SELECT
  USING (true);

ALTER TABLE public.armour ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.hero_images (
  slug text NOT NULL,
  image_id integer NOT NULL REFERENCES public.images (id),
  position integer NOT NULL DEFAULT 0,
  PRIMARY KEY (slug, image_id)
);

CREATE INDEX hero_images_image_id_idx ON public.hero_images (image_id);

CREATE POLICY "Public hero_images are viewable by everyone." ON public.hero_images FOR
SELECT USING (true);

ALTER TABLE public.hero_images ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.image_galleries (
  name text NOT NULL,
  image_id integer NOT NULL REFERENCES public.images (id),
  position integer NOT NULL DEFAULT 0,
  PRIMARY KEY (name, image_id)
);

CREATE INDEX image_galleries_image_id_idx ON public.image_galleries (image_id);

CREATE POLICY "Public image_galleries are viewable by everyone." ON public.image_galleries FOR
SELECT USING (true);

ALTER TABLE public.image_galleries ENABLE ROW LEVEL SECURITY;
