alter table public.unit_profile_weapons
  drop constraint unit_profile_weapons_pkey;
alter table public.unit_profile_weapons
  add column id          integer primary key generated by default as identity,
  add column quantity    integer not null default 1,
  add column alternative integer not null default 0,
  add column position    integer not null default 0,
  add constraint unit_profile_weapons_quantity_ck check (quantity > 0);
create unique index unit_profile_weapons_profile_alt_weapon_key
  on public.unit_profile_weapons (unit_profile_id, alternative, weapon_id);
create table public.unit_profile_armour (
  unit_profile_id  integer not null references public.unit_profiles (id) on delete cascade,
  armour_id        integer not null references public.armour (id),
  position         integer not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz,
  primary key (unit_profile_id, armour_id)
);
alter table public.unit_profile_armour enable row level security;
create policy "Public unit_profile_armour are viewable by everyone."
  on public.unit_profile_armour for select using (true);
insert into public.unit_profile_armour (unit_profile_id, armour_id)
select id, armour_id from public.unit_profiles where armour_id is not null;
alter table public.unit_profiles
  drop constraint unit_profiles_armour_fkey,
  drop column armour_id;
alter table public.unit_profiles
  add column wargear_cards_max integer,
  add constraint unit_profiles_wargear_cards_max_ck
    check (wargear_cards_max is null or wargear_cards_max >= 0);
create table public.army_list_entry_options (
  id                    integer primary key generated by default as identity,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz,
  army_list_entry_id    integer not null references public.army_list_entries (id) on delete cascade,
  unit_profile_id       integer references public.unit_profiles (id),
  weapon_id             integer references public.weapons (id),
  armour_id             integer references public.armour (id),
  vehicle_id            integer references public.vehicles (id),
  wargear_category_id   integer references public.wargear_categories (id),
  to_unit_profile_id    integer references public.unit_profiles (id),
  quantity              integer not null default 1,
  replaces_weapon_id    integer references public.weapons (id),
  replaces_armour_id    integer references public.armour (id),
  points                numeric(5,1),
  points_percent        integer,
  points_basis_id       integer references public.points_bases (id),
  models_max            integer,
  applies_to            text not null default 'model',
  restriction           text,
  alternative           integer not null default 0,
  position              integer not null,
  note                  text,
  constraint army_list_entry_options_grant_ck check (
    (weapon_id is not null)::int
  + (armour_id is not null)::int
  + (vehicle_id is not null)::int
  + (wargear_category_id is not null)::int
  + (to_unit_profile_id is not null)::int <= 1
  ),
  constraint army_list_entry_options_quantity_ck check (quantity > 0),
  constraint army_list_entry_options_applies_to_ck check (applies_to in ('model','mount')),
  constraint army_list_entry_options_models_max_ck
    check (models_max is null or models_max > 0)
);
alter table public.army_list_entry_options enable row level security;
create policy "Public army_list_entry_options are viewable by everyone."
  on public.army_list_entry_options for select using (true);
create index army_list_entry_options_entry_idx
  on public.army_list_entry_options (army_list_entry_id, position);
drop table public.unit_profile_wargear;
alter table public.units
  add column faction_id integer references public.factions (id);
create index units_faction_id_idx on public.units (faction_id);
alter table public.unit_categories
  add column min_percent integer,
  add column max_percent integer,
  add column note        text,
  add constraint unit_categories_percent_ck check (
    (min_percent is null or (min_percent between 0 and 100)) and
    (max_percent is null or (max_percent between 0 and 100)) and
    (min_percent is null or max_percent is null or max_percent >= min_percent)
  );
create table public.army_list_allowance_rules (
  id                  integer primary key generated by default as identity,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz,
  unit_category_id    integer references public.unit_categories (id) on delete cascade,
  army_list_entry_id  integer references public.army_list_entries (id) on delete cascade,
  count               integer not null,
  per_count           integer not null default 1,
  per_entry_id        integer references public.army_list_entries (id),
  per_category_id     integer references public.unit_categories (id),
  note                text,
  constraint army_list_allowance_rules_governs_ck check (
    (unit_category_id is not null)::int + (army_list_entry_id is not null)::int = 1
  ),
  constraint army_list_allowance_rules_per_ck check (
    (per_entry_id is not null)::int + (per_category_id is not null)::int <= 1
  ),
  constraint army_list_allowance_rules_counts_ck check (count >= 0 and per_count > 0)
);
alter table public.army_list_allowance_rules enable row level security;
create policy "Public army_list_allowance_rules are viewable by everyone."
  on public.army_list_allowance_rules for select using (true);
create table public.army_list_allies (
  id                 integer primary key generated by default as identity,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz,
  army_list_id       integer not null references public.army_lists (id) on delete cascade,
  ally_army_list_id  integer references public.army_lists (id),
  ally_faction_id    integer references public.factions (id),
  position           integer not null default 0,
  note               text,
  constraint army_list_allies_target_ck check (
    (ally_army_list_id is not null)::int + (ally_faction_id is not null)::int = 1
  )
);
alter table public.army_list_allies enable row level security;
create policy "Public army_list_allies are viewable by everyone."
  on public.army_list_allies for select using (true);
alter table public.weapons
  add column counts_as_weapon_id integer references public.weapons (id),
  add constraint weapons_counts_as_not_self_ck
    check (counts_as_weapon_id is null or counts_as_weapon_id <> id);
alter table public.wargear_items
  add column restriction text;
alter table public.wargear_items
  alter column points drop not null,
  alter column points type numeric(5,1);
