do $$
    begin
        create type wargear_rarities as enum ('Uncommon', 'Rare', 'Unique');
    exception
        when duplicate_object then null;
    end
$$;

create table if not exists
  public.wargear_cards (
    id int generated by default as identity primary key,
    created_at timestamp with time zone default "now" () not null,
    updated_at timestamp with time zone,
    name text not null,
    availability text not null,
    origin text not null,
    rarity wargear_rarities not null,
    points text,
    restriction text,
    discard_after_use boolean default false not null,
    description text,
    weapon_id int references weapons (id),
    armour_id int references armour (id),
    constraint wargear_cards_name_availability_key unique (name, availability),
    constraint wargear_cards_single_body check (
      (weapon_id is not null)::int
      + (armour_id is not null)::int
      + (description is not null)::int = 1
    )
  );

alter table public.wargear_cards owner to postgres;

create or replace trigger handle_updated_at before
update on public.wargear_cards for each row
execute function extensions.moddatetime ('updated_at');

create policy "Public wargear_cards are viewable by everyone." on public.wargear_cards for
select
  using (true);

alter table public.wargear_cards enable row level security;
