do $$
    begin
        create type armour_categories as enum (
            'Physical Armour',
            'Personal Force Fields',
            'Shields'
        );
    exception
        when duplicate_object then null;
    end
$$;

alter table public.armour
  add column if not exists category armour_categories;

create table if not exists
  public.armour_profiles (
    id int generated by default as identity primary key,
    created_at timestamp with time zone default "now" () not null,
    updated_at timestamp with time zone,
    armour_id int references armour not null,
    save text not null,
    condition text
  );

alter table public.armour_profiles owner to postgres;

create or replace trigger handle_updated_at before
update on public.armour_profiles for each row
execute function extensions.moddatetime ('updated_at');

create policy "Public armour_profiles are viewable by everyone." on public.armour_profiles for
select
  using (true);

alter table public.armour_profiles enable row level security;

create table if not exists
  public.armour_special_rules (
    id int generated by default as identity primary key,
    created_at timestamp with time zone default "now" () not null,
    updated_at timestamp with time zone,
    name text not null unique,
    rule text not null,
    rule_id int references rules
  );

alter table public.armour_special_rules owner to postgres;

create or replace trigger handle_updated_at before
update on public.armour_special_rules for each row
execute function extensions.moddatetime ('updated_at');

create policy "Public armour_special_rules are viewable by everyone." on public.armour_special_rules for
select
  using (true);

alter table public.armour_special_rules enable row level security;

create table if not exists
  public.armour_special_rule_assignments (
    armour_id int references armour not null,
    special_rule_id int references armour_special_rules not null,
    primary key (armour_id, special_rule_id)
  );

alter table public.armour_special_rule_assignments owner to postgres;

create policy "Public armour_special_rule_assignments are viewable by everyone." on public.armour_special_rule_assignments for
select
  using (true);

alter table public.armour_special_rule_assignments enable row level security;
