create table public.points_bases (
  id          integer primary key generated by default as identity,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  name        text not null unique,
  position    integer not null
);
insert into public.points_bases (name, position) values
  ('Per entry',    0),
  ('Per model',    1),
  ('Per base',     2),
  ('See datafax',  3);
alter table public.points_bases enable row level security;
create policy "Public points_bases are viewable by everyone."
  on public.points_bases for select using (true);
alter table public.unit_profiles
  add column m  integer,
  add column ws integer,
  add column bs integer,
  add column s  integer,
  add column t  integer,
  add column w  integer,
  add column i  integer,
  add column a  integer,
  add column ld integer;
update public.unit_profiles up
   set m  = cp.m,  ws = cp.ws, bs = cp.bs,
       s  = cp.s,  t  = cp.t,  w  = cp.w,
       i  = cp.i,  a  = cp.a,  ld = cp.ld
  from public.characteristic_profiles cp
 where cp.id = up.characteristic_profile_id;
alter table public.unit_profiles
  drop constraint unit_profiles_characteristic_profile_id_fkey,
  drop column characteristic_profile_id;
drop table public.characteristic_profiles;
alter table public.unit_profiles rename column min to models_min;
alter table public.unit_profiles rename column max to models_max;
alter table public.unit_profiles alter column models_max drop not null;
alter table public.unit_profiles alter column points type numeric(5,1);
alter table public.unit_profiles add column position integer;
update public.unit_profiles up
   set position = t.rn
  from (
    select id, (row_number() over (partition by unit_id order by id)) - 1 as rn
      from public.unit_profiles
  ) t
 where t.id = up.id;
alter table public.unit_profiles alter column position set not null;
alter table public.unit_profiles rename column armour to armour_id;
alter table public.unit_profiles
  add column created_at timestamptz not null default now(),
  add column updated_at timestamptz;
create table public.army_list_entries (
  id                integer primary key generated by default as identity,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz,
  unit_category_id  integer not null references public.unit_categories (id),
  unit_id           integer not null references public.units (id),
  allowance_min     integer not null default 0,
  allowance_max     integer,
  points            numeric(5,1),
  points_basis_id   integer references public.points_bases (id),
  position          integer not null,
  note              text,
  constraint army_list_entries_allowance_ck
    check (allowance_max is null or allowance_max >= allowance_min)
);
alter table public.army_list_entries enable row level security;
create policy "Public army_list_entries are viewable by everyone."
  on public.army_list_entries for select using (true);
alter table public.unit_categories
  add column created_at timestamptz not null default now(),
  add column updated_at timestamptz;
alter table public.unit_profile_weapons
  add column created_at timestamptz not null default now(),
  add column updated_at timestamptz;
alter table public.unit_profile_wargear
  add column created_at timestamptz not null default now(),
  add column updated_at timestamptz;
alter table public.unit_profile_wargear
  rename column profile_description to note;
alter table public.unit_profiles
  drop constraint unit_profiles_unit_id_fkey,
  add constraint unit_profiles_unit_id_fkey
    foreign key (unit_id) references public.units (id) on delete cascade;
alter table public.unit_profile_weapons
  drop constraint unit_profile_weapons_unit_profile_id_fkey,
  add constraint unit_profile_weapons_unit_profile_id_fkey
    foreign key (unit_profile_id) references public.unit_profiles (id) on delete cascade;
alter table public.unit_profile_wargear
  drop constraint unit_profile_wargear_unit_profile_id_fkey,
  add constraint unit_profile_wargear_unit_profile_id_fkey
    foreign key (unit_profile_id) references public.unit_profiles (id) on delete cascade;
create unique index unit_profiles_unit_id_position_key
  on public.unit_profiles (unit_id, position);
create unique index unit_categories_army_list_id_position_key
  on public.unit_categories (army_list_id, position);
create unique index army_list_entries_category_position_key
  on public.army_list_entries (unit_category_id, position);
comment on column public.units.unit_category_id is
  'DEPRECATED - superseded by army_list_entries. Dropped in step 2.';
comment on column public.units.points is
  'DEPRECATED - superseded by army_list_entries.points. Dropped in step 2.';
