-- Enum types share a namespace with tables, so the enums are renamed out of the
-- way before the tables take their names. Old columns are retained; they are
-- dropped only once the app code reading category_id is deployed.

alter type public.weapon_categories rename to weapon_categories_enum;
alter type public.armour_categories rename to armour_categories_enum;

create table public.weapon_categories (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  name text not null unique,
  position integer not null unique
);

create table public.armour_categories (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  name text not null unique,
  position integer not null unique
);

alter table public.weapon_categories enable row level security;
alter table public.armour_categories enable row level security;

create policy "Public weapon_categories are viewable by everyone."
  on public.weapon_categories for select using (true);
create policy "Public armour_categories are viewable by everyone."
  on public.armour_categories for select using (true);

create trigger handle_updated_at before update on public.weapon_categories
  for each row execute function moddatetime('updated_at');
create trigger handle_updated_at before update on public.armour_categories
  for each row execute function moddatetime('updated_at');

-- Positions preserve the enum sort order the pages currently rely on.
insert into public.weapon_categories (name, position)
select l.name, l.position from (values
  ('Close combat', 0), ('Pistol', 1), ('Basic', 2),
  ('Heavy', 3), ('Support', 4), ('Grenades', 5)
) as l(name, position);

insert into public.armour_categories (name, position)
select l.name, l.position from (values
  ('Physical Armour', 0), ('Personal Force Fields', 1), ('Shields', 2)
) as l(name, position);

alter table public.weapons
  add column category_id integer references public.weapon_categories(id);
alter table public.armour
  add column category_id integer references public.armour_categories(id);

update public.weapons w
  set category_id = c.id from public.weapon_categories c
  where c.name = w.category::text;
update public.armour a
  set category_id = c.id from public.armour_categories c
  where c.name = a.category::text;

alter table public.weapons alter column category_id set not null;
alter table public.armour alter column category_id set not null;

create index weapons_category_id_idx on public.weapons (category_id);
create index armour_category_id_idx on public.armour (category_id);
