-- Backfill of the schema changes applied as direct SQL on 27 August 2026.
--
-- Batches 0, 2 and 3 followed the then-current convention and went in as plain
-- SQL, so nine objects and four seeds are live but absent from this history.
-- Every statement below is written to be a no-op against the live database and
-- to rebuild the same schema from the files alone.

-- Batch 0 — explicit ordering on the wargear list

alter table public.wargear_items
  add column if not exists position integer not null default 0;

alter table public.wargear_categories
  add column if not exists position integer not null default 0;

-- Batch 0 — Strategy Rating on the profile

alter table public.unit_profiles
  add column if not exists strategy_rating smallint;

-- Batch 0 — wargear cards a profile carries without paying for them

create table if not exists public.unit_profile_wargear_cards (
  unit_profile_id  integer not null references public.unit_profiles (id) on delete cascade,
  wargear_card_id  integer not null references public.wargear_cards (id),
  position         integer not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz,
  primary key (unit_profile_id, wargear_card_id)
);

alter table public.unit_profile_wargear_cards enable row level security;

drop policy if exists "Public unit_profile_wargear_cards are viewable by everyone."
  on public.unit_profile_wargear_cards;
create policy "Public unit_profile_wargear_cards are viewable by everyone."
  on public.unit_profile_wargear_cards for select using (true);

-- Batch 0 — a priced wargear item that is more than one entity

create table if not exists public.wargear_item_components (
  id               integer primary key generated by default as identity,
  wargear_item_id  integer not null references public.wargear_items (id) on delete cascade,
  weapon_id        integer references public.weapons (id),
  armour_id        integer references public.armour (id),
  wargear_card_id  integer references public.wargear_cards (id),
  quantity         integer not null default 1,
  position         integer not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz,
  constraint wargear_item_components_one_target_ck check (
    (weapon_id is not null)::int + (armour_id is not null)::int
  + (wargear_card_id is not null)::int = 1)
);

alter table public.wargear_item_components enable row level security;

drop policy if exists "Public wargear_item_components are viewable by everyone."
  on public.wargear_item_components;
create policy "Public wargear_item_components are viewable by everyone."
  on public.wargear_item_components for select using (true);

-- Batch 2 — armour carried only by one loadout alternative

alter table public.unit_profile_armour
  add column if not exists alternative smallint not null default 0;

-- Batch 2 — a wargear card as the grant of an option

alter table public.unit_options
  add column if not exists wargear_card_id integer references public.wargear_cards (id);

alter table public.unit_options drop constraint if exists unit_options_grant_ck;
alter table public.unit_options add constraint unit_options_grant_ck check (
  (weapon_id is not null)::int + (armour_id is not null)::int
+ (granted_unit_id is not null)::int + (to_unit_profile_id is not null)::int
+ (wargear_card_id is not null)::int <= 1);

alter table public.army_list_entry_options
  add column if not exists wargear_card_id integer references public.wargear_cards (id);

alter table public.army_list_entry_options
  drop constraint if exists army_list_entry_options_grant_ck;
alter table public.army_list_entry_options add constraint army_list_entry_options_grant_ck check (
  (weapon_id is not null)::int + (armour_id is not null)::int
+ (granted_unit_id is not null)::int + (wargear_category_id is not null)::int
+ (to_unit_profile_id is not null)::int + (wargear_card_id is not null)::int <= 1);

-- Batch 3 — where a datafax was first printed

alter table public.datafaxes add column if not exists origin text;
alter table public.datafaxes alter column origin set not null;

comment on column public.datafaxes.origin is 'Publication the datafax was first printed in. Never the Datafax Collection compilation, which is a binder of reprints; where a card was reprinted, the earliest printing, and one row per card rather than one per book. Records the publication, not the printing that was scanned.';

-- Seeds applied with the same batches. Ids are stated so a rebuild reproduces
-- the live keys, which the data dumps reference.

insert into public.points_bases (id, name, position)
select 5, 'Per model upgrade', 4
where not exists (select 1 from public.points_bases where name = 'Per model upgrade');

insert into public.armour (id, name, category_id)
select 20, 'Rosarius', 2
where not exists (select 1 from public.armour where name = 'Rosarius');

insert into public.armour_profiles (id, armour_id, save)
select 19, a.id, '4+'
from public.armour a
where a.name = 'Rosarius'
  and not exists (select 1 from public.armour_profiles p where p.armour_id = a.id);

insert into public.armour (id, name, category_id)
select 21, 'Scout Armour', 1
where not exists (select 1 from public.armour where name = 'Scout Armour');

insert into public.armour_profiles (id, armour_id, save)
select 20, a.id, '4+'
from public.armour a
where a.name = 'Scout Armour'
  and not exists (select 1 from public.armour_profiles p where p.armour_id = a.id);

insert into public.unit_types (id, name, position, plural_name)
select 7, 'Support', 2, 'Support'
where not exists (select 1 from public.unit_types where name = 'Support');

update public.unit_types set position = 3 where name = 'Vehicle';
update public.unit_types set position = 4 where name = 'Fortification';

delete from public.unit_types where name = 'Field Defence';

select setval(pg_get_serial_sequence('public.points_bases', 'id'),
  (select max(id) from public.points_bases));
select setval(pg_get_serial_sequence('public.armour', 'id'),
  (select max(id) from public.armour));
select setval(pg_get_serial_sequence('public.armour_profiles', 'id'),
  (select max(id) from public.armour_profiles));
select setval(pg_get_serial_sequence('public.unit_types', 'id'),
  (select max(id) from public.unit_types));
