-- Allowance sets (ruling 45, CIG-3), with the wording rulings of 24 September 2026.

create table public.army_list_allowance_sets (
  id            integer primary key generated by default as identity,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz,
  army_list_id  integer not null references public.army_lists (id) on delete cascade,
  name          text,
  singular      text,
  position      integer not null,
  unique (army_list_id, name),
  unique (army_list_id, position),
  constraint army_list_allowance_sets_singular_ck check ((name is null) = (singular is null))
);

alter table public.army_list_allowance_sets enable row level security;

create policy "Public army_list_allowance_sets are viewable by everyone."
  on public.army_list_allowance_sets for select using (true);

comment on table public.army_list_allowance_sets is 'A group of entries that an allowance rule governs, or counts against, as one thing.';
comment on column public.army_list_allowance_sets.name is 'The plural the lines print: clan mobs. Null names the set by its members.';
comment on column public.army_list_allowance_sets.singular is 'The singular: clan mob. Set with name, or null with it.';

create table public.army_list_allowance_set_entries (
  set_id              integer not null references public.army_list_allowance_sets (id) on delete cascade,
  army_list_entry_id  integer not null references public.army_list_entries (id),
  position            integer not null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz,
  primary key (set_id, army_list_entry_id),
  unique (set_id, position)
);

alter table public.army_list_allowance_set_entries enable row level security;

create policy "Public army_list_allowance_set_entries are viewable by everyone"
  on public.army_list_allowance_set_entries for select using (true);

comment on table public.army_list_allowance_set_entries is 'One entry in an allowance set, in the order the lines name it.';

alter table public.army_list_allowance_rules
  add column set_id      integer references public.army_list_allowance_sets (id) on delete cascade,
  add column per_set_id  integer references public.army_list_allowance_sets (id),
  add column per_rule_id integer references public.army_list_allowance_rules (id),
  add column qualifier   text,
  add column label       text;

alter table public.army_list_allowance_rules
  drop constraint army_list_allowance_rules_governs_ck,
  add constraint army_list_allowance_rules_governs_ck check (
    (unit_category_id is not null)::int
  + (army_list_entry_id is not null)::int
  + (set_id is not null)::int = 1
  ),
  drop constraint army_list_allowance_rules_per_ck,
  add constraint army_list_allowance_rules_per_ck check (
    (per_entry_id is not null)::int
  + (per_category_id is not null)::int
  + (per_set_id is not null)::int
  + (per_rule_id is not null)::int <= 1
  ),
  add constraint army_list_allowance_rules_per_rule_not_self_ck
    check (per_rule_id is null or per_rule_id <> id);

comment on column public.army_list_allowance_rules.set_id is 'The set this rule governs, where one allowance is shared by several entries.';
comment on column public.army_list_allowance_rules.per_set_id is 'The set the allowance is counted against: each entry taken from it earns the count.';
comment on column public.army_list_allowance_rules.per_rule_id is 'The rule the allowance is counted against: each unit actually taken under that rule earns the count.';
comment on column public.army_list_allowance_rules.qualifier is 'Printed after the generated line, following a comma. A rule with a qualifier is never merged.';
comment on column public.army_list_allowance_rules.label is 'The singular for a unit taken under this rule, printed by any rule counted per this one: regimental squad.';
