-- Ruling 7, 2 September 2026. Sub-organisation headings printed within a band
-- of an army list (Imperial Agents first, then Eldar and Chaos) get a model of
-- their own rather than being folded into an entry note.

create table public.army_list_entry_groups (
  id            integer primary key generated by default as identity,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz,
  army_list_id  integer not null references public.army_lists (id) on delete cascade,
  name          text not null,
  position      integer not null,
  unique (army_list_id, name),
  unique (army_list_id, position)
);

alter table public.army_list_entry_groups enable row level security;

create policy "Public army_list_entry_groups are viewable by everyone."
  on public.army_list_entry_groups for select using (true);

alter table public.army_list_entries
  add column entry_group_id integer references public.army_list_entry_groups (id);

comment on table public.army_list_entry_groups is 'Sub-organisation headings printed inside a band of an army list. Entries sharing one render under a single sub-heading, in position order.';
