-- Ruling 18, 3 September 2026: unit special rules, on the weapon/armour special-rule shape.

create table public.unit_special_rules (
  id          integer primary key generated by default as identity,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  name        text not null unique,
  rule        text,
  rule_id     integer references public.rules (id),
  anchor      text,
  faction_id  integer references public.factions (id),
  constraint unit_special_rules_body_ck check (rule is not null or rule_id is not null)
);

create or replace trigger handle_updated_at before
update on public.unit_special_rules for each row
execute function extensions.moddatetime ('updated_at');

alter table public.unit_special_rules enable row level security;

create policy "Public unit_special_rules are viewable by everyone."
  on public.unit_special_rules for select using (true);

comment on table public.unit_special_rules is 'A named special rule a unit entry prints. Prose of its own, a pointer at a rules-chapter rule, or both.';
comment on column public.unit_special_rules.rule is 'The rule''s own prose, as rendered HTML. Null where the row is only a pointer at a rules-chapter rule.';
comment on column public.unit_special_rules.rule_id is 'The rules-chapter rule this names. Set for rules the core chapters already hold; null for faction-specific ones.';
comment on column public.unit_special_rules.anchor is 'The fragment to link within the target rule, where it differs from the rule''s own anchor — Dispersed Formation sits inside Squad Coherency. Null links to the rule itself.';
comment on column public.unit_special_rules.faction_id is 'Grouping only, for a faction rules page. Never load-bearing: the assignment carries the association.';

create table public.unit_special_rule_assignments (
  id               integer primary key generated by default as identity,
  unit_id          integer not null references public.units (id) on delete cascade,
  special_rule_id  integer not null references public.unit_special_rules (id) on delete cascade,
  position         integer not null default 0,
  note             text,
  unique (unit_id, special_rule_id)
);

create index unit_special_rule_assignments_unit_id_idx on public.unit_special_rule_assignments (unit_id);

alter table public.unit_special_rule_assignments enable row level security;

create policy "Public unit_special_rule_assignments are viewable by everyone."
  on public.unit_special_rule_assignments for select using (true);

comment on table public.unit_special_rule_assignments is 'One printed special rule on one unit, in printed order.';
comment on column public.unit_special_rule_assignments.note is 'The per-unit variable of a shared rule, as rendered HTML — Hive Mind''s 12" against 18", Carapace''s 5+ against 4+.';
