alter table wargear_categories add column faction_id integer references factions (id);

update wargear_categories w
set faction_id = a.faction_id
from army_lists a
where a.id = w.army_list_id;

alter table wargear_categories
  alter column faction_id set not null,
  drop column army_list_id,
  add constraint wargear_categories_faction_category_uk unique (faction_id, category);

comment on column wargear_categories.faction_id is 'The faction whose Wargear List prints this section. A unit reaches its own faction''s sections and every ancestor''s.';

create table unit_options (
  id                  integer generated by default as identity primary key,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz,
  unit_id             integer not null references units (id) on delete cascade,
  unit_profile_id     integer references unit_profiles (id) on delete cascade,
  weapon_id           integer references weapons (id),
  armour_id           integer references armour (id),
  granted_unit_id     integer references units (id),
  to_unit_profile_id  integer references unit_profiles (id),
  replaces_weapon_id  integer references weapons (id),
  replaces_armour_id  integer references armour (id),
  quantity            smallint not null default 1,
  models_max          smallint,
  models_per          smallint,
  whole_unit          boolean not null default false,
  alternative         smallint not null default 0,
  optional            boolean not null default true,
  restriction         text,
  note                text,
  position            integer not null,
  constraint unit_options_grant_ck check (
    (weapon_id is not null)::int + (armour_id is not null)::int
  + (granted_unit_id is not null)::int + (to_unit_profile_id is not null)::int <= 1),
  constraint unit_options_quantity_ck check (quantity > 0),
  constraint unit_options_models_ck   check (models_max is null or models_max > 0),
  constraint unit_options_ratio_ck    check (models_per is null or models_per > 1),
  constraint unit_options_scope_ck    check (not (whole_unit and models_max is not null))
);

create index unit_options_unit_id_idx on unit_options (unit_id);

comment on column unit_options.models_per is 'Ratio denominator: models_max 1 with models_per 3 is "up to one in three".';
comment on column unit_options.whole_unit is 'True where the option applies to every model at once rather than to a number of them.';

create table unit_option_categories (
  unit_option_id      integer not null references unit_options (id) on delete cascade,
  wargear_category_id integer not null references wargear_categories (id),
  position            smallint not null default 0,
  primary key (unit_option_id, wargear_category_id)
);

alter table unit_options enable row level security;
alter table unit_option_categories enable row level security;

create policy "Enable read access for all users" on unit_options for select using (true);
create policy "Enable read access for all users" on unit_option_categories for select using (true);
