-- Rulings 44 to 52, 11 September 2026. Three printings the schema could not say.
--
-- CIG-1 (ruling 44): the Imperial Guard Veteran Abilities section prices ten
-- abilities that are rules, not weapons or armour, so a wargear item may now
-- point at a special rule. wargear_items carried no target check at all; one is
-- written here over all four targets, which every live row already satisfies.
--
-- CIG-3 (ruling 45): the Guard regimental structure counts a named set of
-- entries against another set, and a second tier against the first rule. Sets
-- are entries grouped under a name; a rule may govern a set and be paid for per
-- set or per rule. Ruling 49's base_count rides on the same alter.
--
-- M1 (rulings 46, 49, 50, 51, 52): a rule the page gives one model in a unit;
-- "one, and one more for each X"; a character taken as another entry; a cap on
-- models across the army; an option that buys one profile of a multi-profile
-- weapon. All nullable, so no live row changes meaning.

-- CIG-1, ruling 44

alter table public.wargear_items
  add column special_rule_id integer references public.unit_special_rules (id);

alter table public.wargear_items
  add constraint wargear_items_target_ck check (
    (armour_id is not null)::int
  + (weapon_id is not null)::int
  + (unit_id is not null)::int
  + (special_rule_id is not null)::int = 1
  );

comment on column public.wargear_items.special_rule_id is 'The special rule this item buys, where the printed section prices an ability rather than a weapon, armour or a vehicle''s datafax — the Imperial Guard Veteran Abilities.';

-- CIG-3, ruling 45, with base_count from ruling 49

create table public.army_list_allowance_sets (
  id            integer primary key generated by default as identity,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz,
  army_list_id  integer not null references public.army_lists (id) on delete cascade,
  name          text not null,
  position      integer not null,
  unique (army_list_id, name),
  unique (army_list_id, position)
);

alter table public.army_list_allowance_sets enable row level security;

create policy "Public army_list_allowance_sets are viewable by everyone."
  on public.army_list_allowance_sets for select using (true);

comment on table public.army_list_allowance_sets is 'A named group of entries an allowance rule counts as one thing. The Guard''s three Command squad entries are one set, so a rule keyed to it need not be written three times.';

create table public.army_list_allowance_set_entries (
  set_id              integer not null references public.army_list_allowance_sets (id) on delete cascade,
  army_list_entry_id  integer not null references public.army_list_entries (id) on delete cascade,
  position            integer not null default 0,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz,
  primary key (set_id, army_list_entry_id)
);

alter table public.army_list_allowance_set_entries enable row level security;

create policy "Public army_list_allowance_set_entries are viewable by everyone."
  on public.army_list_allowance_set_entries for select using (true);

alter table public.army_list_allowance_rules
  add column set_id      integer references public.army_list_allowance_sets (id) on delete cascade,
  add column per_set_id  integer references public.army_list_allowance_sets (id),
  add column per_rule_id integer references public.army_list_allowance_rules (id),
  add column base_count  integer;

alter table public.army_list_allowance_rules
  drop constraint army_list_allowance_rules_governs_ck,
  add constraint army_list_allowance_rules_governs_ck check (
    (unit_category_id is not null)::int
  + (army_list_entry_id is not null)::int
  + (set_id is not null)::int = 1
  ),
  drop constraint army_list_allowance_rules_per_ck,
  add constraint army_list_allowance_rules_per_ck check (
    (per_entry_id is not null)::int
  + (per_category_id is not null)::int
  + (per_set_id is not null)::int
  + (per_rule_id is not null)::int = 1
  ),
  add constraint army_list_allowance_rules_per_rule_not_self_ck
    check (per_rule_id is null or per_rule_id <> id),
  add constraint army_list_allowance_rules_base_count_ck
    check (base_count is null or base_count >= 0);

comment on column public.army_list_allowance_rules.set_id is 'The set this rule governs, where the allowance is shared across several entries rather than held by one.';
comment on column public.army_list_allowance_rules.per_set_id is 'The set the allowance is counted against, where any entry in it earns the same allowance.';
comment on column public.army_list_allowance_rules.per_rule_id is 'The rule the allowance is counted against, for a second tier: one further unit for each unit the rule above already allows.';
comment on column public.army_list_allowance_rules.base_count is 'The allowance before any per-count is added, so "one, and one more for each X" is base_count 1 with count 1. Null where the printing gives no base.';

-- M1, rulings 46, 50, 51, 52

create unique index unit_profiles_unit_id_id_key
  on public.unit_profiles (unit_id, id);

alter table public.unit_special_rule_assignments
  add column unit_profile_id integer,
  add constraint unit_special_rule_assignments_unit_profile_fk
    foreign key (unit_id, unit_profile_id)
    references public.unit_profiles (unit_id, id) on delete cascade;

-- one rule may reach several profiles of one unit, so the profile joins the key
alter table public.unit_special_rule_assignments
  drop constraint unit_special_rule_assignments_unit_id_special_rule_id_key,
  add constraint unit_special_rule_assignments_unit_rule_profile_key
    unique nulls not distinct (unit_id, special_rule_id, unit_profile_id);

comment on column public.unit_special_rule_assignments.unit_profile_id is 'The profile this rule attaches to, where the page gives it to one model of the unit — the Wolf Scout Sergeant''s Marine rules. Null means the whole unit.';

alter table public.army_list_entries
  add column counts_as_entry_id integer references public.army_list_entries (id) on delete set null,
  add column models_max_army    integer,
  add constraint army_list_entries_counts_as_not_self_ck
    check (counts_as_entry_id is null or counts_as_entry_id <> id),
  add constraint army_list_entries_models_max_army_ck
    check (models_max_army is null or models_max_army > 0);

comment on column public.army_list_entries.counts_as_entry_id is 'The entry this one is taken as, so it consumes that entry''s allowance — Ulrik as a Wolf Priest. Null on every entry taken in its own right.';
comment on column public.army_list_entries.models_max_army is 'The most models of this unit the army may field across every entry of it. Null where the printing caps nothing.';

create unique index weapon_profiles_weapon_id_id_key
  on public.weapon_profiles (weapon_id, id);

alter table public.unit_options
  add column weapon_profile_id integer,
  add constraint unit_options_weapon_profile_fk
    foreign key (weapon_id, weapon_profile_id)
    references public.weapon_profiles (weapon_id, id),
  add constraint unit_options_weapon_profile_ck
    check (weapon_profile_id is null or weapon_id is not null);

alter table public.army_list_entry_options
  add column weapon_profile_id integer,
  add constraint army_list_entry_options_weapon_profile_fk
    foreign key (weapon_id, weapon_profile_id)
    references public.weapon_profiles (weapon_id, id),
  add constraint army_list_entry_options_weapon_profile_ck
    check (weapon_profile_id is null or weapon_id is not null);

comment on column public.unit_options.weapon_profile_id is 'The one profile of a multi-profile weapon this option buys — the Tarantula''s five fits. Null takes the weapon whole.';
comment on column public.army_list_entry_options.weapon_profile_id is 'The one profile of a multi-profile weapon this price is for. Null prices the weapon whole.';
