alter table public.units add column type_text text;
update public.units set type_text = type::text;
alter table public.units drop column type;
drop type public.unit_types;
create table public.unit_types (
  id          integer primary key generated by default as identity,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  name        text not null unique,
  position    integer not null
);
insert into public.unit_types (name, position) values
  ('Character',     0),
  ('Squad',         1),
  ('Vehicle',       2),
  ('Fortification', 3),
  ('Field Defence', 4);
alter table public.unit_types enable row level security;
create policy "Public unit_types are viewable by everyone."
  on public.unit_types for select using (true);
alter table public.units add column unit_type_id integer references public.unit_types (id);
update public.units u set unit_type_id = ut.id
  from public.unit_types ut where ut.name = u.type_text;
alter table public.units alter column unit_type_id set not null;
alter table public.units drop column type_text;
create table public.motive_types (
  id          integer primary key generated by default as identity,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  name        text not null unique,
  position    integer not null
);
insert into public.motive_types (name, position) values
  ('Tracked',         0),
  ('Wheeled',         1),
  ('Bikes & Trikes',  2),
  ('Walkers',         3),
  ('Skimmers',        4);
alter table public.motive_types enable row level security;
create policy "Public motive_types are viewable by everyone."
  on public.motive_types for select using (true);
create table public.datafaxes (
  id                  integer primary key generated by default as identity,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz,
  unit_id             integer not null unique references public.units (id) on delete cascade,
  points              numeric(5,1),
  motive_type_id      integer references public.motive_types (id),
  speed_slow          integer,
  speed_combat        integer,
  speed_fast          integer,
  ram_value           integer,
  crew                integer,
  transport_capacity  integer,
  open_topped         boolean,
  large_target        boolean,
  capacity_inside     integer,
  capacity_roof       integer,
  deployment          text,
  location_dice       text not null default 'D6',
  note                text,
  constraint datafaxes_speeds_ck check (
    (speed_slow   is null or speed_slow   >= 0) and
    (speed_combat is null or speed_combat >= 0) and
    (speed_fast   is null or speed_fast   >= 0)
  ),
  constraint datafaxes_crew_ck check (crew is null or crew >= 0)
);
alter table public.datafaxes enable row level security;
create policy "Public datafaxes are viewable by everyone."
  on public.datafaxes for select using (true);
create table public.datafax_weapons (
  id                  integer primary key generated by default as identity,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz,
  datafax_id          integer not null references public.datafaxes (id) on delete cascade,
  weapon_id           integer not null references public.weapons (id),
  mount               text,
  firing_arc_degrees  integer,
  arc_note            text,
  linked_group        integer,
  quantity            integer not null default 1,
  position            integer not null,
  constraint datafax_weapons_arc_ck
    check (firing_arc_degrees is null or firing_arc_degrees between 1 and 360),
  constraint datafax_weapons_quantity_ck check (quantity > 0)
);
alter table public.datafax_weapons enable row level security;
create policy "Public datafax_weapons are viewable by everyone."
  on public.datafax_weapons for select using (true);
create index datafax_weapons_datafax_idx on public.datafax_weapons (datafax_id, position);
create table public.damage_charts (
  id          integer primary key generated by default as identity,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  datafax_id  integer not null references public.datafaxes (id) on delete cascade,
  name        text not null,
  dice        text not null default 'D6',
  note        text,
  position    integer not null,
  unique (datafax_id, name)
);
alter table public.damage_charts enable row level security;
create policy "Public damage_charts are viewable by everyone."
  on public.damage_charts for select using (true);
create table public.damage_chart_results (
  id               integer primary key generated by default as identity,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz,
  damage_chart_id  integer not null references public.damage_charts (id) on delete cascade,
  roll_min         integer not null,
  roll_max         integer not null,
  effect           text not null,
  position         integer not null,
  constraint damage_chart_results_band_ck check (roll_max >= roll_min)
);
alter table public.damage_chart_results enable row level security;
create policy "Public damage_chart_results are viewable by everyone."
  on public.damage_chart_results for select using (true);
create index damage_chart_results_chart_idx
  on public.damage_chart_results (damage_chart_id, position);
create table public.datafax_locations (
  id                 integer primary key generated by default as identity,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz,
  datafax_id         integer not null references public.datafaxes (id) on delete cascade,
  roll_min           integer not null,
  roll_max           integer not null,
  name               text not null,
  armour_front       integer,
  armour_side_rear   integer,
  datafax_weapon_id  integer references public.datafax_weapons (id) on delete set null,
  damage_chart_id    integer references public.damage_charts (id),
  damage_anchor      text,
  note               text,
  position           integer not null,
  constraint datafax_locations_band_ck check (roll_max >= roll_min),
  constraint datafax_locations_damage_ck
    check (damage_chart_id is null or damage_anchor is null)
);
alter table public.datafax_locations enable row level security;
create policy "Public datafax_locations are viewable by everyone."
  on public.datafax_locations for select using (true);
create index datafax_locations_datafax_idx
  on public.datafax_locations (datafax_id, position);
alter table public.wargear_items
  drop constraint wargear_items_vehicle_id_fkey;
alter table public.wargear_items
  rename column vehicle_id to unit_id;
alter table public.wargear_items
  add constraint wargear_items_unit_id_fkey
    foreign key (unit_id) references public.units (id);
alter table public.army_list_entry_options
  drop constraint army_list_entry_options_vehicle_id_fkey;
alter table public.army_list_entry_options
  rename column vehicle_id to granted_unit_id;
alter table public.army_list_entry_options
  add constraint army_list_entry_options_granted_unit_id_fkey
    foreign key (granted_unit_id) references public.units (id);
drop table public.vehicles;
